name: flake8_and_pytest-check

on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip install poetry
          make install
      - name: run linter
        run: make lint
      - name: run pytest
        run: make test